sudo: required
services:
  - docker

before_install:
  - docker build -t tarunkoli0206/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tarunkoli0206/react-test npm test

after_success:
  - docker build -t tarunkoli0206/multi-client ./client
  - docker build -t tarunkoli0206/multi-nginx ./nginx
  - docker build -t tarunkoli0206/multi-server ./server
  - docker build -t tarunkoli0206/multi-worker ./worker
